[workspace]
resolver = "2"
members = [
    "crates/rat-branches",
    "crates/rat-canvas",
    "crates/rat-diff",
    "crates/rat-editor",
    "crates/rat-image",
    "crates/rat-keymap",
    "crates/rat-layers",
    "crates/rat-leaderkey",
    "crates/rat-markdown",
    "crates/rat-selection",
    "crates/rat-streaming",
    "crates/rat-table",
    "crates/rat-widgets",
    "crates/rat-nodegraph",
    "crates/rat-spreadsheet",
    "crates/rat-tree",
    "crates/showcase",
]

[workspace.package]
edition = "2024"
license = "MIT"

[workspace.dependencies]
ratatui = "0.30"
unicode-width = "0.2"
base64 = "0.22"
