use std::fs;
use std::io::ErrorKind;
use std::process::Command;

const SHOWCASE_BINARY: &str = env!("CARGO_BIN_EXE_showcase");
const EXPORT_TYPST_ARG: &str = "--export-typst";
const HELP_ARG: &str = "--help";
const TYPST_BINARY: &str = "typst";
const TYPST_COMPILE_ARG: &str = "compile";
const TEMP_PREFIX: &str = "subwayrat_showcase_export_test";
const TYPST_EXTENSION: &str = "typ";
const PDF_EXTENSION: &str = "pdf";
const GENERATED_MARKER: &str = "Generated by rat-typst";
const HELP_MARKER: &str = "--export-typst";

#[test]
fn export_typst_writes_compilable_document() {
    let temp_dir = std::env::temp_dir();
    let unique_name = format!("{TEMP_PREFIX}_{}", std::process::id());
    let typst_path = temp_dir.join(format!("{unique_name}.{TYPST_EXTENSION}"));
    let pdf_path = temp_dir.join(format!("{unique_name}.{PDF_EXTENSION}"));
    let _ = fs::remove_file(&typst_path);
    let _ = fs::remove_file(&pdf_path);

    let output = Command::new(SHOWCASE_BINARY)
        .arg(EXPORT_TYPST_ARG)
        .arg(&typst_path)
        .output()
        .expect("run showcase export");

    assert!(
        output.status.success(),
        "showcase export failed: {}",
        String::from_utf8_lossy(&output.stderr),
    );
    let document = fs::read_to_string(&typst_path).expect("read generated typst");
    assert!(document.contains(GENERATED_MARKER));

    let compile_output = Command::new(TYPST_BINARY)
        .arg(TYPST_COMPILE_ARG)
        .arg(&typst_path)
        .arg(&pdf_path)
        .output();
    let compile_output = match compile_output {
        Ok(output) => output,
        Err(error) if error.kind() == ErrorKind::NotFound => return,
        Err(error) => panic!("failed to run typst: {error}"),
    };

    assert!(
        compile_output.status.success(),
        "typst compile failed: {}",
        String::from_utf8_lossy(&compile_output.stderr),
    );
    assert!(fs::metadata(&pdf_path).expect("compiled pdf exists").len() > 0);

    let _ = fs::remove_file(typst_path);
    let _ = fs::remove_file(pdf_path);
}

#[test]
fn help_mentions_typst_export_without_running_tui() {
    let output = Command::new(SHOWCASE_BINARY)
        .arg(HELP_ARG)
        .output()
        .expect("run showcase help");

    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains(HELP_MARKER));
}

#[test]
fn unknown_argument_fails_instead_of_entering_tui() {
    let output = Command::new(SHOWCASE_BINARY)
        .arg("--not-a-real-showcase-flag")
        .output()
        .expect("run showcase with invalid flag");

    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("unknown showcase argument"));
}
